import {
  SENS_SERVICE_ID,
  SENS_ACCESS_KEY,
  SENS_SECRET_KEY,
  WORK_PHONE_NUMBER,
  FIREBASE_API_KEY,
} from '@env';

export default {
  SENS_SERVICE_ID,
  SENS_SECRET_KEY,
  SENS_ACCESS_KEY,
  WORK_PHONE_NUMBER,
  FIREBASE_API_KEY,
};
